CREATE TABLE [dbo].[Expense] (
	[Id] [uniqueidentifier] NOT NULL,
	[Amount] [decimal](19, 4) NOT NULL,
	CONSTRAINT [PK_Expense] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)ON [PRIMARY]
) ON [PRIMARY]